import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import type { Plugin } from "vite";

/**
 * How many previous builds' hashed chunks stay on disk beside the current one.
 *
 * One is the number that matters, because it is the number that turns the failure this
 * plugin exists for into a non-failure: a tab that was open across a single rebuild asks
 * for chunks the *previous* build emitted, and one retained generation is exactly enough to
 * answer it. Two would cover a tab that survived two rebuilds, which is a development-loop
 * shape rather than a deployment one, and the disk is not free — see the header below.
 */
const RETAINED_BUILDS = 1;

/**
 * Where the list of generations lives.
 *
 * Deliberately *not* inside `outDir`: everything in there is served by the SPA route in
 * `presentation/web/app.py`, and a build ledger is not a public asset. `node_modules/.tmp`
 * is where this project already keeps build state — both `tsconfig.*.json` point their
 * `tsBuildInfoFile` at it.
 *
 * **Losing it is not a safe degradation, and this comment used to say it was.** An absent or
 * unreadable ledger makes the next build retain nothing, so `buildStart` deletes the previous
 * generation — the entry chunk an open tab is holding included — and that is precisely the
 * failure this plugin exists to remove, arriving by the back door. It is the `emptyOutDir:
 * true` behaviour the plugin replaces, which makes it no worse than before the plugin and no
 * better than it either; calling that "safe" reads as a designed fallback rather than as the
 * hole it is. `rm -rf node_modules` is the ordinary way to reach it, because the ledger lives
 * under there and nothing else does. So `buildStart` says so on the console when it happens:
 * a window that closed silently cannot be told from one that never opened, and the reader who
 * dead-ends afterwards is the one person who cannot see either.
 */
const LEDGER = "node_modules/.tmp/grace-window.json";

function assetNames(assets: string): string[] {
  if (!existsSync(assets)) return [];
  return readdirSync(assets);
}

function readLedger(root: string): string[][] {
  try {
    const parsed: unknown = JSON.parse(readFileSync(join(root, LEDGER), "utf8"));
    if (!Array.isArray(parsed)) return [];
    // Shape-checked rather than trusted. This file is regenerated by every build and is
    // never edited by hand, so a malformed one means a half-written file or a stale format,
    // and the safe reading of both is "retain nothing".
    return parsed.filter(
      (generation): generation is string[] =>
        Array.isArray(generation) && generation.every((name) => typeof name === "string"),
    );
  } catch {
    return [];
  }
}

function writeLedger(root: string, generations: string[][]): void {
  const path = join(root, LEDGER);
  mkdirSync(join(root, "node_modules/.tmp"), { recursive: true });
  writeFileSync(path, JSON.stringify(generations), "utf8");
}

/**
 * Keep the previous build's chunks so a tab that outlives a build does not dead-end.
 *
 * **The failure this removes.** Two routes in `App.tsx` are `lazy()` and the Atlas layout
 * engine is behind a dynamic import, so those chunks are fetched at use time and not at load.
 * A tab that has been open since before a build holds a module graph naming that build's
 * hashed filenames. `emptyOutDir: true` deleted them, so opening the review a reader had been
 * looking at asked for a file that no longer existed. It is not a development artefact: it
 * fires for every user who is mid-session across a deployment, and the longer a tab lives the
 * likelier it is.
 *
 * **Why keeping the old files is safe.** Every emitted chunk is content-hashed, so a build
 * that changes a byte changes the name and two builds' outputs cannot collide. Only
 * `index.html` has to be current, and it is overwritten by every build and served
 * `no-cache` (`_static_cache_headers` in `presentation/web/app.py`, asserted by
 * `tests/integration/test_cache_headers.py`). So a *new* visitor is never served a stale
 * name, and an *old* tab is served exactly the names it already knows.
 *
 * **What it costs, measured on this branch.** A single build into an empty tree leaves
 * `assets/` at 18 files and 4,035,665 bytes. After a build that changed one string literal in
 * `App.tsx` the directory held 28 files and 6,491,996 bytes — 1.61 times the one-build figure
 * rather than twice it, because a chunk whose bytes did not change keeps its hash and so is
 * one file in both generations. It is bounded rather than cumulative: a third and a fourth
 * consecutive literal-changing build left it at exactly 28 files and 6,491,996 bytes, because
 * `buildStart` prunes to `RETAINED_BUILDS` generations before the new one is written. (All
 * four figures from `ls … | wc -l` and `find … -exec stat -f %z` summed over
 * `src/archcompass/presentation/web/static/assets` between successive `make frontend-build`
 * runs. A *string literal* and not a comment: comments are stripped before hashing, so a
 * comment-only edit emits the same content hashes and measures nothing.) The directory is
 * gitignored and untracked — `.gitignore` line 20, and `git ls-files` on it returns nothing —
 * so none of this reaches the repository. A wheel built from a dirty tree would carry the
 * spare generation, because `pyproject.toml` includes `src` wholesale; a CI wheel is built
 * from a fresh checkout where `assets/` starts empty, so it carries one.
 *
 * **What still gets a clean tree.** Everything outside `assets/` is deleted at
 * `buildStart`, which is what `emptyOutDir: true` did for the whole directory: `index.html`
 * and the copied `public/` files are current with no leftovers. Nothing in this repository
 * enumerates the assets directory and expects one build's worth — the only readers are
 * `STATIC_DIR` in `presentation/web/app.py`, which resolves one requested path at a time,
 * and `BUNDLE` in `tests/browser/harness.py`, which is `index.html`.
 *
 * **And the one thing the window does not cover is the entry document.** `index.html` is
 * deleted at `buildStart` and written back at the end, so a build that is interrupted between
 * those two points leaves none at all, and `spa` in `presentation/web/app.py` then answers
 * every route `503 frontend_not_built` until a build finishes. Verified by killing
 * `vite build` three seconds in: `static/` was left holding `assets/` and nothing else, and
 * the app answered `{"code":"frontend_not_built",…}` for `/`. It is not a regression —
 * `emptyOutDir: true` had exactly the same hole — and it is not one this plugin can close,
 * because the retained generation is *chunks*, and the single document that names them has to
 * be current or it is worse than absent. It is written down because the paragraph above
 * enumerates what survives a build, and this is what does not.
 *
 * How wide that is, and what else goes with it, measured by sampling `static/` every 50 ms
 * across an `npm run build` with two generations on disk: at 3.95 s — the instant `tsc -b`
 * finishes and rollup calls `buildStart` — `assets/` fell from 28 files to 18 and
 * `index.html` disappeared in the same sample, and the document stayed absent for the
 * remaining 9.56 s of a 13.71 s build. Both halves of that are `buildStart` doing its
 * pruning *before* anything is written, so an interrupted build has already spent the older
 * generation and left no document, at second zero of the part that emits.
 *
 * **The window is finite, and what is past it is a screen rather than machinery.** A tab open
 * across two builds still asks for a name that is gone. There is no automatic recovery behind
 * this any more — there was, and it could loop — so that tab lands on the chunk case in
 * `src/app/error-boundary.tsx`, which names the fault and offers the reload that fixes it.
 *
 * **Three routes fetch a chunk by name, not the two.** `/reviews/:id` and `/policies` are the
 * `lazy()` routes `src/App.tsx` names, and a tab that walks to either past the window lands on
 * that screen. `/` is the third and is not on that list: the landing page mounts
 * `CaseFileDocket` through a `lazy()` of its own, so the chunk is fetched by name there too.
 * Measured by loading `/reviews` in a tab, rebuilding from an emptied `assets/` with both
 * chunks changed, and walking to `/`: three requests and three 404s — `exhibit`,
 * `finding-detail` and `highlight`, which the preload helper asks for together — and the
 * console line `Failed to fetch dynamically imported module: …/exhibit-*.js`. That tab does
 * not reach the reload screen and must not: `ExhibitBoundary` at `landing-page.tsx:604`
 * catches it first, so the failure costs one section of a marketing page instead of the page,
 * and it deliberately offers no reload. Correct behaviour, third affected route — `/` belongs
 * with the two, not with the five routes that live wholly inside the entry chunk.
 */
export function graceWindow(root: string): Plugin {
  let retained: string[][] = [];
  let outDir = "";

  return {
    name: "archcompass:grace-window",
    // Build only. `vite dev` serves modules from memory off the source tree, so there is no
    // output directory to keep a generation of.
    apply: "build",

    // Taken from the resolved config rather than recomputed from `root`. The output
    // directory is already declared once, in `vite.config.ts`; a second copy of the path
    // here would be a thing that can disagree with it, and would disagree silently — the
    // plugin would prune a directory nothing is building into and retain nothing at all.
    configResolved(config) {
      outDir = resolve(config.root, config.build.outDir);
    },

    buildStart() {
      const ledger = readLedger(root);
      retained = ledger.slice(0, RETAINED_BUILDS);
      const keep = new Set(retained.flat());
      if (!existsSync(outDir)) return;

      for (const entry of readdirSync(outDir)) {
        // `assets/` is pruned per generation just below; everything else is emptied, which
        // is what `emptyOutDir` did for the whole tree.
        if (entry === "assets") continue;
        rmSync(join(outDir, entry), { recursive: true, force: true });
      }
      const assets = join(outDir, "assets");
      const present = assetNames(assets);
      // The one case where this plugin is about to do the thing it exists to prevent, said
      // out loud. No ledger and chunks on disk means every one of them goes, including the
      // entry chunk an open tab is holding — see `LEDGER` above for why that is the hole and
      // not the fallback. Chunks with no ledger is the first build after `rm -rf
      // node_modules`; an empty `assets/` is an ordinary first build and says nothing.
      if (retained.length === 0 && present.length > 0) {
        console.warn(
          `archcompass:grace-window: no readable ledger at ${LEDGER}, so this build retains ` +
            `nothing and deletes ${present.length} chunk(s) an open tab may still be asking ` +
            `for. A tab open across this build lands on an error fallback instead of the ` +
            `screen it asked for, until it is reloaded.`,
        );
      }
      for (const name of present) {
        if (keep.has(name)) continue;
        rmSync(join(assets, name), { force: true });
      }
    },

    /**
     * The new generation is the bundle's own list of what it wrote, and it has to be.
     *
     * Reading it back as "whatever is on disk that was not retained" looks equivalent and is
     * wrong for the commonest build of all: a rebuild with no source change emits the same
     * content hashes, so that difference is empty, and an empty generation recorded here
     * makes the *next* build retain nothing and delete every chunk a live tab is holding —
     * the exact failure this plugin exists to remove, reintroduced by a no-op. Naming the
     * files the build emitted is right in both cases, because that is the set a document
     * served this `index.html` can ask for, and it makes an unchanged rebuild a no-op rather
     * than a reset: two consecutive `make frontend-build` runs with no source change leave
     * the ledger as two generations of 18 names each, not one empty one and one full one.
     * `grace-window.test.ts` drives that third build, which is where the difference shows.
     *
     * Only the entries under `assets/`. `index.html` and the copied `public/` files live at
     * the root, which is emptied and rewritten by every build, so they have no generations.
     */
    writeBundle(_options, bundle) {
      const fresh = Object.keys(bundle)
        .filter((name) => name.startsWith("assets/"))
        .map((name) => name.slice("assets/".length));
      writeLedger(root, [fresh, ...retained].slice(0, RETAINED_BUILDS + 1));
    },
  };
}
