/* eslint-disable */
/**
 * Generated by scripts/generate_openapi_types.py from FastAPI's OpenAPI schema.
 * Do not edit this file directly.
 */

export interface components {
  schemas: {
    "AnswerProgress": components["schemas"]["AnswerProse"] | components["schemas"]["QuestionAnswered"] | components["schemas"]["QuestionFailed"];
    "AnswerProse": {
    "event"?: "prose";
    "text": string;
  };
    "AnsweredQuestions": {
    "review_id": string;
    "answers": Array<components["schemas"]["RecordedAnswer"]>;
  };
    "ArchitectureCase": {
    "schema_version"?: 2;
    "case_id"?: string;
    "title": string;
    "problem_statement"?: string;
    "desired_outcome"?: string;
    "actors_and_workflows"?: Array<string>;
    "functional_requirements"?: Array<string>;
    "quality_attributes"?: Array<string>;
    "technical_constraints"?: Array<string>;
    "organisational_constraints"?: Array<string>;
    "expected_future_changes"?: Array<string>;
    "non_goals"?: Array<string>;
    "confirmed_facts"?: Array<components["schemas"]["CaseStatement"]>;
    "derived_constraints"?: Array<components["schemas"]["CaseStatement"]>;
    "assumptions"?: Array<components["schemas"]["CaseStatement"]>;
    "unresolved_questions"?: Array<components["schemas"]["CaseStatement"]>;
    "design_forces"?: Array<components["schemas"]["CaseStatement"]>;
    "clarifications"?: Array<components["schemas"]["Clarification"]>;
    "repository"?: components["schemas"]["RepositoryReference"] | null;
    "policy_applicability"?: components["schemas"]["PolicyApplicabilityContext"];
    "referenced_policy_ids"?: Array<string>;
    "candidate_alternatives"?: Array<components["schemas"]["CaseAlternative"]>;
    "reversal_conditions"?: Array<string>;
    "revisit_triggers"?: Array<string>;
    "created_at"?: string;
    "updated_at"?: string;
    "revision"?: number;
  };
    "AtlasEdge": {
    "edge_id": string;
    "source_id": string;
    "target_id": string;
    "edge_type": components["schemas"]["EdgeType"];
    "confidence": number;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "resolved_by"?: "parse" | "types";
    "conformance"?: "strict" | "structural" | null;
  };
    "AtlasExploreRequest": {
    "root_path": string;
    "operation": "children" | "dependencies" | "dependants" | "callers" | "implementations" | "tests" | "forward_neighbourhood" | "reverse_neighbourhood" | "search" | "shortest_path" | "cycles" | "signals";
    "node_id"?: string | null;
    "target_id"?: string | null;
    "terms"?: Array<string>;
    "signal_codes"?: Array<string>;
    "depth"?: number;
    "limit"?: number;
  };
    "AtlasMetricValue": {
    "node_id": string;
    "metric": string;
    "value": number;
    "rank"?: number | null;
    "nature"?: components["schemas"]["MetricNature"];
    "scope"?: components["schemas"]["MetricScope"];
    "definition"?: string;
    "limitations"?: string;
  };
    "AtlasNodeSummary": {
    "node_id": string;
    "qualified_name": string;
    "node_type": components["schemas"]["NodeType"];
    "path": string;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "is_public"?: boolean | null;
  };
    "AtlasQueryResult": {
    "query": components["schemas"]["RepositorySummaryQuery"] | components["schemas"]["SubsystemSummaryQuery"] | components["schemas"]["NodeDetailsQuery"] | components["schemas"]["RelationQuery"] | components["schemas"]["NeighbourhoodQuery"] | components["schemas"]["ShortestPathQuery"] | components["schemas"]["CyclesQuery"] | components["schemas"]["SignalsQuery"] | components["schemas"]["HotspotsQuery"] | components["schemas"]["SearchNodesQuery"] | components["schemas"]["SourceExcerptQuery"] | components["schemas"]["ReviewContextQuery"];
    "node_ids"?: Array<string>;
    "summary"?: string;
    "node_summaries"?: Array<components["schemas"]["AtlasNodeSummary"]>;
    "metric_values"?: Array<components["schemas"]["AtlasMetricValue"]>;
    "relationships"?: Array<components["schemas"]["AtlasEdge"]>;
    "test_ids"?: Array<string>;
    "signals"?: Array<components["schemas"]["ObscuritySignal"]>;
    "excerpts"?: Array<components["schemas"]["SourceExcerpt"]>;
  };
    "AtlasVersion": {
    "schema_version"?: number;
    "version_id"?: string;
    "repository_identity": string;
    "root_path": string;
    "git_commit_sha"?: string | null;
    "content_fingerprint": string;
    "parser_version": string;
    "analysis_config_hash": string;
    "created_at"?: string;
  };
    "AvailableModelResponse": {
    "provider": string;
    "model": string;
    "thinking"?: boolean | null;
    "label"?: string;
    "input_token_limit"?: number | null;
    "output_token_limit"?: number | null;
    "is_selected"?: boolean;
  };
    "BoundaryExcerpt": {
    "reference": string;
    "qualified_name": string;
    "role": string;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "text"?: string;
    "unavailable"?: string;
  };
    "BoundaryReview": {
    "schema_version"?: 1;
    "review_id"?: string;
    "status": components["schemas"]["ReviewStatus"];
    "case_id": string;
    "case_revision": number;
    "atlas_version_id": string;
    "reasoning_model": string;
    "prompt_identity": string;
    "elicited_from"?: string | null;
    "report"?: components["schemas"]["BoundaryReviewReport"] | null;
    "markdown_report"?: string | null;
    "duration_seconds"?: number;
    "sanitized_errors"?: Array<string>;
    "failure_diagnostics"?: Array<components["schemas"]["FailureDiagnostic"]>;
    "created_at"?: string;
  };
    "BoundaryReviewReport": {
    "schema_version"?: 3;
    "report_id"?: string;
    "case_title": string;
    "problem_and_desired_outcome": string;
    "reviewed"?: Array<components["schemas"]["ReviewedBoundary"]>;
    "overview": components["schemas"]["ReviewOverview"];
    "policies_presented"?: Array<string>;
    "excerpts"?: Array<components["schemas"]["BoundaryExcerpt"]>;
  };
    "BoundaryReviewSummary": {
    "review_id": string;
    "case_id": string;
    "case_revision": number;
    "atlas_version_id": string;
    "status": string;
    "boundaries_detected": number | null;
    "boundaries_reviewed": number;
    "boundaries_material": number;
    "created_at": string;
    "updated_at": string;
    "case_title"?: string | null;
    "elicited_from"?: string | null;
  };
    "BundledCase": {
    "name": string;
    "title": string;
    "problem_statement": string;
    "repository_root": string;
    "has_expected_answers": boolean;
  };
    "CaseAlternative": {
    "id"?: string;
    "title": string;
    "summary": string;
  };
    "CaseField": "expected_future_changes" | "confirmed_facts" | "technical_constraints" | "non_goals" | "assumptions";
    "CaseRevision": {
    "case_id": string;
    "revision": number;
    "snapshot": components["schemas"]["ArchitectureCase"];
    "event_type": "created" | "user_update";
    "actor": string;
    "answered"?: components["schemas"]["AnsweredQuestions"] | null;
    "created_at"?: string;
  };
    "CaseStatement": {
    "id"?: string;
    "text": string;
    "kind": components["schemas"]["StatementKind"];
    "source"?: string | null;
  };
    "CaseSummary": {
    "case_id": string;
    "revision": number;
    "title": string;
    "problem_statement": string;
    "repository_root"?: string | null;
    "updated_at": string;
  };
    "CaseUpdate": {
    "title"?: string | null;
    "problem_statement"?: string | null;
    "desired_outcome"?: string | null;
    "actors_and_workflows"?: Array<string> | null;
    "functional_requirements"?: Array<string> | null;
    "quality_attributes"?: Array<string> | null;
    "technical_constraints"?: Array<string> | null;
    "organisational_constraints"?: Array<string> | null;
    "expected_future_changes"?: Array<string> | null;
    "non_goals"?: Array<string> | null;
    "confirmed_facts"?: Array<components["schemas"]["CaseStatement"]> | null;
    "derived_constraints"?: Array<components["schemas"]["CaseStatement"]> | null;
    "assumptions"?: Array<components["schemas"]["CaseStatement"]> | null;
    "unresolved_questions"?: Array<components["schemas"]["CaseStatement"]> | null;
    "design_forces"?: Array<components["schemas"]["CaseStatement"]> | null;
    "clarifications"?: Array<components["schemas"]["Clarification"]> | null;
    "repository"?: components["schemas"]["RepositoryReference"] | null;
    "policy_applicability"?: components["schemas"]["PolicyApplicabilityContext"] | null;
    "referenced_policy_ids"?: Array<string> | null;
    "candidate_alternatives"?: Array<components["schemas"]["CaseAlternative"]> | null;
    "reversal_conditions"?: Array<string> | null;
    "revisit_triggers"?: Array<string> | null;
  };
    "Clarification": {
    "id"?: string;
    "question": string;
    "answer": string;
    "bears_on": components["schemas"]["CaseField"];
  };
    "CyclesQuery": {
    "kind": "cyclic_components";
    "limit"?: number;
  };
    "DirectoryEntry": {
    "name": string;
    "path": string;
  };
    "DirectoryListing": {
    "path": string;
    "parent": string | null;
    "directories": Array<components["schemas"]["DirectoryEntry"]>;
  };
    "EdgeType": "contains" | "imports" | "calls" | "inherits" | "implements" | "references" | "tests" | "configures";
    "FailureDiagnostic": {
    "code": components["schemas"]["FailureDiagnosticCode"];
    "force_handles"?: Array<string>;
    "count"?: number | null;
  };
    "FailureDiagnosticCode": "cluster_count_out_of_range" | "unknown_force_references" | "missing_force_references" | "duplicate_force_references" | "duplicate_cluster_ids";
    "FindingCandidate": {
    "candidate_id"?: string;
    "pattern": components["schemas"]["FindingPattern"];
    "summary": string;
    "participants": Array<components["schemas"]["FindingParticipant"]>;
    "measurements"?: Array<components["schemas"]["FindingMeasurement"]>;
    "relationships"?: Array<components["schemas"]["AtlasEdge"]>;
    "limitations": string;
  };
    "FindingMeasurement": {
    "name": string;
    "value": number;
    "unit"?: string;
    "nature"?: components["schemas"]["MetricNature"];
    "definition"?: string;
    "limitations"?: string;
  };
    "FindingParticipant": {
    "node_id": string;
    "qualified_name": string;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "role": string;
  };
    "FindingPattern": "sole_implementation" | "duplicated_knowledge" | "scattered_concept";
    "HotspotsQuery": {
    "kind": "hotspots";
    "metric": string;
    "limit"?: number;
  };
    "MetricNature": "objective_measurement" | "structural_proxy";
    "MetricScope": "lexical_node" | "owning_module" | "reverse_static_impact_neighbourhood" | "bounded_resolved_call_chain";
    "ModelCatalogResponse": {
    "providers": Array<components["schemas"]["ProviderAvailabilityResponse"]>;
    "candidates": Array<components["schemas"]["AvailableModelResponse"]>;
  };
    "ModelIdentity": {
    "provider": string;
    "model": string;
    "thinking"?: boolean | null;
  };
    "ModelSelectionRequest": {
    "provider": string;
    "model": string;
    "thinking"?: boolean | null;
  };
    "NeighbourhoodQuery": {
    "kind": "forward_neighbourhood" | "reverse_neighbourhood";
    "node_id": string;
    "depth"?: number;
    "limit"?: number;
  };
    "NodeDetailsQuery": {
    "kind": "node_details";
    "node_id": string;
  };
    "NodeType": "repository" | "package" | "module" | "class" | "function" | "method" | "interface" | "test_module" | "test_function" | "configuration";
    "ObscuritySignal": {
    "code": string;
    "message": string;
    "node_id": string;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "nature"?: components["schemas"]["MetricNature"];
    "definition"?: string;
    "limitations"?: string;
  };
    "OpenQuestion": {
    "reference": string;
    "what_the_review_saw": string;
    "unknown": string;
    "why_it_matters": string;
    "question": string;
    "answer_belongs_in": components["schemas"]["CaseField"];
    "supporting_references": Array<string>;
  };
    "OverviewStatement": {
    "text": string;
    "supporting_references": Array<string>;
  };
    "PolicyApplicabilityContext": {
    "user"?: string | null;
    "organisation"?: string | null;
    "repository"?: string | null;
  };
    "PolicyBearing": {
    "policy_id": string;
    "policy_title": string;
    "how": string;
  };
    "PolicyDocument": {
    "schema_version"?: 2;
    "id": string;
    "title": string;
    "description"?: string | null;
    "scope": components["schemas"]["PolicyScope"];
    "applies_to"?: string | null;
    "strength": components["schemas"]["PolicyStrength"];
    "tags": Array<string>;
    "source": components["schemas"]["PolicySource"];
    "body": string;
    "source_path": string;
    "content_hash": string;
    "origin"?: components["schemas"]["PolicyOrigin"];
  };
    "PolicyDraft": {
    "title": string;
    "description": string;
    "body": string;
    "tags"?: Array<string>;
    "strength": components["schemas"]["PolicyStrength"];
  };
    "PolicyOrigin": "external" | "workspace";
    "PolicyScope": "general" | "user" | "organisation" | "repository" | "accepted_adr";
    "PolicySource": {
    "author": string;
    "inspiration"?: Array<string>;
  };
    "PolicySourceRegistration": {
    "canonical_path": string;
    "registered_at"?: string;
  };
    "PolicySourceRemovalResponse": {
    "removed": boolean;
  };
    "PolicySourceRequest": {
    "source": string;
  };
    "PolicyStrength": "guidance" | "preferred" | "required";
    "ProblemDetail": {
    "code": string;
    "message": string;
    "retryable"?: boolean;
    "field_errors"?: Array<string>;
  };
    "ProviderAvailabilityResponse": {
    "provider": string;
    "available": boolean;
    "detail"?: string;
    "probed_at": string;
  };
    "QuestionAnswered": {
    "event"?: "answered";
    "message": components["schemas"]["ReviewMessage"];
  };
    "QuestionFailed": {
    "event"?: "failed";
    "problem": components["schemas"]["ProblemDetail"];
  };
    "RecordedAnswer": {
    "question_reference": string;
    "answer_belongs_in": components["schemas"]["CaseField"];
    "recorded_text": string;
  };
    "RelationQuery": {
    "kind": "direct_dependencies" | "direct_dependants" | "known_callers" | "implementations" | "related_tests";
    "node_id": string;
    "limit"?: number;
  };
    "RepositoryPathRequest": {
    "root_path": string;
  };
    "RepositoryReference": {
    "root_path": string;
    "atlas_version_id"?: string | null;
  };
    "RepositorySummary": {
    "version_id": string;
    "repository_identity": string;
    "root_path": string;
    "git_commit_sha"?: string | null;
    "created_at": string;
    "node_count"?: number;
    "edge_count"?: number;
    "signal_count"?: number;
  };
    "RepositorySummaryQuery": {
    "kind": "repository_summary";
    "limit"?: number;
  };
    "ReviewAnswer": {
    "answer": string;
    "supporting_references"?: Array<string>;
    "suggested_answer"?: string;
  };
    "ReviewAnswersRequest": {
    "answers": Array<components["schemas"]["SubmittedAnswer"]>;
  };
    "ReviewCompleted": {
    "event"?: "completed";
    "review": components["schemas"]["BoundaryReview"];
  };
    "ReviewContextQuery": {
    "kind": "review_context";
    "node_ids": Array<string>;
    "limit"?: number;
  };
    "ReviewContextRequest": {
    "root_path": string;
    "node_ids": Array<string>;
    "limit"?: number;
  };
    "ReviewConversation": {
    "schema_version"?: 1;
    "conversation_id"?: string;
    "review_id": string;
    "case_id": string;
    "case_revision": number;
    "title": string;
    "question_reference"?: string | null;
    "messages"?: Array<components["schemas"]["ReviewMessage"]>;
    "created_at"?: string;
  };
    "ReviewConversationCreateRequest": {
    "review_id": string;
    "title"?: string | null;
    "question_reference"?: string | null;
  };
    "ReviewDetected": {
    "event"?: "detected";
    "total": number;
    "boundaries": Array<string>;
  };
    "ReviewEliciting": {
    "event"?: "eliciting";
    "total": number;
  };
    "ReviewFailed": {
    "event"?: "failed";
    "problem": components["schemas"]["ProblemDetail"];
  };
    "ReviewJudged": {
    "event"?: "judged";
    "position": number;
    "total": number;
    "abstraction": string;
    "material": boolean;
  };
    "ReviewMessage": {
    "message_id"?: string;
    "ordinal": number;
    "question": string;
    "answer"?: components["schemas"]["ReviewAnswer"] | null;
    "failure"?: string;
    "asked_at"?: string;
  };
    "ReviewOverview": {
    "situation": string;
    "themes"?: Array<components["schemas"]["OverviewStatement"]>;
    "recommended_sequence"?: Array<components["schemas"]["OverviewStatement"]>;
    "limits": string;
    "open_questions"?: Array<components["schemas"]["OpenQuestion"]>;
  };
    "ReviewProgress": components["schemas"]["ReviewStarted"] | components["schemas"]["ReviewDetected"] | components["schemas"]["ReviewJudged"] | components["schemas"]["ReviewEliciting"] | components["schemas"]["ReviewSummarising"] | components["schemas"]["ReviewCompleted"] | components["schemas"]["ReviewFailed"];
    "ReviewQuestionRequest": {
    "question": string;
  };
    "ReviewRequest": {
    "case_id": string;
    "repository_root": string;
    "elicited_from"?: string | null;
  };
    "ReviewStarted": {
    "event"?: "started";
    "review_id": string;
    "case_id": string;
    "case_revision": number;
    "elicited_from"?: string | null;
  };
    "ReviewStatus": "running" | "awaiting_answers" | "succeeded" | "failed" | "cancelled";
    "ReviewSummarising": {
    "event"?: "summarising";
    "total": number;
  };
    "ReviewedBoundary": {
    "reference": string;
    "candidate": components["schemas"]["FindingCandidate"];
    "material": boolean;
    "rationale": string;
    "policy_bearings"?: Array<components["schemas"]["PolicyBearing"]>;
    "hinge"?: components["schemas"]["VerdictHinge"] | null;
    "recommended_response"?: string;
    "verdict_label": string;
  };
    "SearchNodesQuery": {
    "kind": "search_nodes";
    "terms": Array<string>;
    "limit"?: number;
  };
    "ShortestPathQuery": {
    "kind": "shortest_dependency_path";
    "source_id": string;
    "target_id": string;
  };
    "SignalsQuery": {
    "kind": "signals";
    "codes"?: Array<string>;
    "limit"?: number;
  };
    "SourceExcerpt": {
    "node_id": string;
    "location": components["schemas"]["SourceLocation"];
    "text": string;
  };
    "SourceExcerptQuery": {
    "kind": "source_excerpt";
    "node_id": string;
    "context_lines"?: number;
    "max_lines"?: number;
  };
    "SourceLocation": {
    "path": string;
    "start_line": number;
    "end_line": number;
  };
    "StatementKind": "fact" | "derived_constraint" | "assumption" | "question" | "force";
    "SubmittedAnswer": {
    "question_reference": string;
    "recorded_text": string;
  };
    "SubsystemSummaryQuery": {
    "kind": "subsystem_summary";
    "node_id": string;
    "limit"?: number;
  };
    "VerdictHinge": {
    "unknown": string;
    "if_confirmed": string;
    "if_denied": string;
  };
    "WorkspaceModels": {
    "reasoning"?: components["schemas"]["ModelIdentity"] | null;
    "failure"?: string;
    "pinned"?: boolean;
  };
    "WorkspaceSummaryResponse": {
    "workspace": string;
    "models": components["schemas"]["WorkspaceModels"];
    "hosted"?: boolean;
  };
  };
}

export interface operations {
  "add_policy_source_api_policies_sources_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["PolicySourceRequest"];
    responses: {
      "201": components["schemas"]["PolicySourceRegistration"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "answer_review_questions_api_reviews__review_id__answers_post": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewAnswersRequest"];
    responses: {
      "201": components["schemas"]["CaseRevision"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "ask_review_question_api_review_conversations__conversation_id__messages_post": {
    parameters: {
      query: never;
      path: {
      "conversation_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewQuestionRequest"];
    responses: {
      "201": components["schemas"]["ReviewMessage"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "cancel_review_api_reviews__review_id__cancel_post": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["BoundaryReview"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "case_history_api_cases__case_id__history_get": {
    parameters: {
      query: never;
      path: {
      "case_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["CaseRevision"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "clear_model_selection_api_models_selection_delete": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "create_case_api_cases_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ArchitectureCase"];
    responses: {
      "201": components["schemas"]["CaseRevision"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "create_policy_api_policies_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["PolicyDraft"];
    responses: {
      "201": components["schemas"]["PolicyDocument"];
      "422": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "create_review_api_reviews_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewRequest"];
    responses: {
      "201": components["schemas"]["BoundaryReview"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "create_review_conversation_api_review_conversations_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewConversationCreateRequest"];
    responses: {
      "201": components["schemas"]["ReviewConversation"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "delete_policy_api_policies__policy_id__delete": {
    parameters: {
      query: never;
      path: {
      "policy_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "delete_review_api_reviews__review_id__delete": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "get_case_api_cases__case_id__get": {
    parameters: {
      query: {
      "revision"?: number | null;
      };
      path: {
      "case_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["CaseRevision"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "get_policy_api_policies__policy_id__get": {
    parameters: {
      query: {
      "repository_root"?: string | null;
      };
      path: {
      "policy_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["PolicyDocument"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "get_review_api_reviews__review_id__get": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["BoundaryReview"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "get_review_conversation_api_review_conversations__conversation_id__get": {
    parameters: {
      query: never;
      path: {
      "conversation_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ReviewConversation"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "import_case_yaml_api_cases_import_yaml_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: string;
    responses: {
      "201": components["schemas"]["CaseRevision"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "index_repository_api_repositories_index_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["RepositoryPathRequest"];
    responses: {
      "201": components["schemas"]["AtlasVersion"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_bundled_cases_api_bundled_cases_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["BundledCase"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_cases_api_cases_get": {
    parameters: {
      query: {
      "limit"?: number;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["CaseSummary"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_directories_api_filesystem_directories_get": {
    parameters: {
      query: {
      "path"?: string | null;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["DirectoryListing"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_policies_api_policies_get": {
    parameters: {
      query: {
      "repository_root"?: string | null;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["PolicyDocument"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_policy_sources_api_policies_sources_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["PolicySourceRegistration"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_repositories_api_repositories_get": {
    parameters: {
      query: {
      "limit"?: number;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["RepositorySummary"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_review_conversations_api_review_conversations_get": {
    parameters: {
      query: {
      "review_id": string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["ReviewConversation"]>;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "list_reviews_api_reviews_get": {
    parameters: {
      query: {
      "case_id"?: string | null;
      "limit"?: number;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["BoundaryReviewSummary"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "load_bundled_case_api_bundled_cases__name__load_post": {
    parameters: {
      query: never;
      path: {
      "name": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "201": components["schemas"]["CaseRevision"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "model_catalog_api_models_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ModelCatalogResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "remove_policy_source_api_policies_sources_delete": {
    parameters: {
      query: {
      "source": string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["PolicySourceRemovalResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_explore_api_repositories_explore_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["AtlasExploreRequest"];
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_hotspots_api_repositories_hotspots_get": {
    parameters: {
      query: {
      "root_path": string;
      "metric"?: string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_inspect_api_repositories_inspect_get": {
    parameters: {
      query: {
      "root_path": string;
      "node_id": string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_review_context_api_repositories_review_context_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewContextRequest"];
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_summary_api_repositories_summary_get": {
    parameters: {
      query: {
      "root_path": string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "review_report_api_reviews__review_id__report_get": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": unknown;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "review_source_api_reviews__review_id__source_get": {
    parameters: {
      query: {
      "reference"?: string | null;
      "context_lines"?: number;
      };
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["BoundaryExcerpt"]>;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "select_model_api_models_selection_put": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ModelSelectionRequest"];
    responses: {
      "200": components["schemas"]["WorkspaceSummaryResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "start_from_repository_api_repositories_start_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["RepositoryPathRequest"];
    responses: {
      "201": components["schemas"]["CaseRevision"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "stream_review_api_reviews_stream_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewRequest"];
    responses: {
      "200": components["schemas"]["ReviewProgress"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "stream_review_question_api_review_conversations__conversation_id__messages_stream_post": {
    parameters: {
      query: never;
      path: {
      "conversation_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewQuestionRequest"];
    responses: {
      "200": components["schemas"]["AnswerProgress"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "update_case_api_cases__case_id__patch": {
    parameters: {
      query: never;
      path: {
      "case_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["CaseUpdate"];
    responses: {
      "200": components["schemas"]["CaseRevision"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "update_policy_api_policies__policy_id__put": {
    parameters: {
      query: never;
      path: {
      "policy_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["PolicyDraft"];
    responses: {
      "200": components["schemas"]["PolicyDocument"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "workspace_summary_api_workspace_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["WorkspaceSummaryResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
}

export interface paths {
  "/api/bundled-cases": {
    get: operations["list_bundled_cases_api_bundled_cases_get"];
  };
  "/api/bundled-cases/{name}/load": {
    post: operations["load_bundled_case_api_bundled_cases__name__load_post"];
  };
  "/api/cases": {
    get: operations["list_cases_api_cases_get"];
    post: operations["create_case_api_cases_post"];
  };
  "/api/cases/import-yaml": {
    post: operations["import_case_yaml_api_cases_import_yaml_post"];
  };
  "/api/cases/{case_id}": {
    get: operations["get_case_api_cases__case_id__get"];
    patch: operations["update_case_api_cases__case_id__patch"];
  };
  "/api/cases/{case_id}/history": {
    get: operations["case_history_api_cases__case_id__history_get"];
  };
  "/api/filesystem/directories": {
    get: operations["list_directories_api_filesystem_directories_get"];
  };
  "/api/models": {
    get: operations["model_catalog_api_models_get"];
  };
  "/api/models/selection": {
    put: operations["select_model_api_models_selection_put"];
    delete: operations["clear_model_selection_api_models_selection_delete"];
  };
  "/api/policies": {
    get: operations["list_policies_api_policies_get"];
    post: operations["create_policy_api_policies_post"];
  };
  "/api/policies/sources": {
    get: operations["list_policy_sources_api_policies_sources_get"];
    post: operations["add_policy_source_api_policies_sources_post"];
    delete: operations["remove_policy_source_api_policies_sources_delete"];
  };
  "/api/policies/{policy_id}": {
    get: operations["get_policy_api_policies__policy_id__get"];
    put: operations["update_policy_api_policies__policy_id__put"];
    delete: operations["delete_policy_api_policies__policy_id__delete"];
  };
  "/api/repositories": {
    get: operations["list_repositories_api_repositories_get"];
  };
  "/api/repositories/explore": {
    post: operations["repository_explore_api_repositories_explore_post"];
  };
  "/api/repositories/hotspots": {
    get: operations["repository_hotspots_api_repositories_hotspots_get"];
  };
  "/api/repositories/index": {
    post: operations["index_repository_api_repositories_index_post"];
  };
  "/api/repositories/inspect": {
    get: operations["repository_inspect_api_repositories_inspect_get"];
  };
  "/api/repositories/review-context": {
    post: operations["repository_review_context_api_repositories_review_context_post"];
  };
  "/api/repositories/start": {
    post: operations["start_from_repository_api_repositories_start_post"];
  };
  "/api/repositories/summary": {
    get: operations["repository_summary_api_repositories_summary_get"];
  };
  "/api/review-conversations": {
    get: operations["list_review_conversations_api_review_conversations_get"];
    post: operations["create_review_conversation_api_review_conversations_post"];
  };
  "/api/review-conversations/{conversation_id}": {
    get: operations["get_review_conversation_api_review_conversations__conversation_id__get"];
  };
  "/api/review-conversations/{conversation_id}/messages": {
    post: operations["ask_review_question_api_review_conversations__conversation_id__messages_post"];
  };
  "/api/review-conversations/{conversation_id}/messages/stream": {
    post: operations["stream_review_question_api_review_conversations__conversation_id__messages_stream_post"];
  };
  "/api/reviews": {
    get: operations["list_reviews_api_reviews_get"];
    post: operations["create_review_api_reviews_post"];
  };
  "/api/reviews/stream": {
    post: operations["stream_review_api_reviews_stream_post"];
  };
  "/api/reviews/{review_id}": {
    get: operations["get_review_api_reviews__review_id__get"];
    delete: operations["delete_review_api_reviews__review_id__delete"];
  };
  "/api/reviews/{review_id}/answers": {
    post: operations["answer_review_questions_api_reviews__review_id__answers_post"];
  };
  "/api/reviews/{review_id}/cancel": {
    post: operations["cancel_review_api_reviews__review_id__cancel_post"];
  };
  "/api/reviews/{review_id}/report": {
    get: operations["review_report_api_reviews__review_id__report_get"];
  };
  "/api/reviews/{review_id}/source": {
    get: operations["review_source_api_reviews__review_id__source_get"];
  };
  "/api/workspace": {
    get: operations["workspace_summary_api_workspace_get"];
  };
}
