/* eslint-disable */
/**
 * Generated by scripts/generate_openapi_types.py from FastAPI's OpenAPI schema.
 * Do not edit this file directly.
 */

export interface components {
  schemas: {
    "AddressedCandidateResponse": {
    "candidate_id": string;
    "title": string;
    "last_seen_review_id": string;
    "last_verdict": string;
  };
    "AnswerResponse": {
    "question": components["schemas"]["QuestionResponse"];
    "status": string;
    "value": string | null;
    "actor": string;
    "answered_at": string;
  };
    "AnswerStatus": "answered" | "skipped";
    "AtlasEdge": {
    "edge_id": string;
    "source_id": string;
    "target_id": string;
    "edge_type": components["schemas"]["EdgeType"];
    "confidence": number;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "resolved_by"?: "parse" | "types";
    "conformance"?: "strict" | "structural" | null;
  };
    "AtlasExploreRequest": {
    "root_path": string;
    "operation": "subsystem_summary" | "direct_dependencies" | "direct_dependants" | "known_callers" | "implementations" | "related_tests" | "forward_neighbourhood" | "reverse_neighbourhood" | "search_nodes" | "shortest_dependency_path" | "cyclic_components" | "signals";
    "node_id"?: string | null;
    "target_id"?: string | null;
    "terms"?: Array<string>;
    "signal_codes"?: Array<string>;
    "depth"?: number;
    "limit"?: number;
  };
    "AtlasMetricValue": {
    "node_id": string;
    "metric": string;
    "value": number;
    "rank"?: number | null;
    "nature"?: components["schemas"]["MetricNature"];
    "scope"?: components["schemas"]["MetricScope"];
    "definition"?: string;
    "limitations"?: string;
  };
    "AtlasNodeSummary": {
    "node_id": string;
    "qualified_name": string;
    "node_type": components["schemas"]["NodeType"];
    "path": string;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "is_public"?: boolean | null;
  };
    "AtlasQueryResult": {
    "query": components["schemas"]["RepositorySummaryQuery"] | components["schemas"]["SubsystemSummaryQuery"] | components["schemas"]["NodeDetailsQuery"] | components["schemas"]["RelationQuery"] | components["schemas"]["NeighbourhoodQuery"] | components["schemas"]["ShortestPathQuery"] | components["schemas"]["CyclesQuery"] | components["schemas"]["SignalsQuery"] | components["schemas"]["HotspotsQuery"] | components["schemas"]["SearchNodesQuery"] | components["schemas"]["SourceExcerptQuery"] | components["schemas"]["ReviewContextQuery"];
    "node_ids"?: Array<string>;
    "summary"?: string;
    "node_summaries"?: Array<components["schemas"]["AtlasNodeSummary"]>;
    "metric_values"?: Array<components["schemas"]["AtlasMetricValue"]>;
    "relationships"?: Array<components["schemas"]["AtlasEdge"]>;
    "test_ids"?: Array<string>;
    "signals"?: Array<components["schemas"]["ObscuritySignal"]>;
    "excerpts"?: Array<components["schemas"]["SourceExcerpt"]>;
  };
    "AtlasResponse": {
    "id": string;
    "repository": components["schemas"]["RepositoryResponse"];
    "node_count": number;
    "edge_count": number;
    "metric_count": number;
    "fact_count": number;
    "signal_count": number;
    "parser_configuration": {
    [key: string]: string;
  };
  };
    "AtlasVersion": {
    "schema_version"?: number;
    "version_id"?: string;
    "repository_identity": string;
    "root_path": string;
    "git_commit_sha"?: string | null;
    "root_commit_sha"?: string | null;
    "branch_name"?: string | null;
    "repo_id"?: string | null;
    "branch_id"?: string | null;
    "content_fingerprint": string;
    "parser_version": string;
    "analysis_config_hash": string;
    "created_at"?: string;
  };
    "AvailableModelResponse": {
    "provider": string;
    "model": string;
    "thinking"?: boolean | "minimal" | "low" | "medium" | "high" | null;
    "label"?: string;
    "input_token_limit"?: number | null;
    "output_token_limit"?: number | null;
    "is_selected"?: boolean;
  };
    "BranchDecisionsResponse": {
    "branch_id": string;
    "decisions": Array<components["schemas"]["DecisionResponse"]>;
  };
    "BranchLineage": {
    "branch_id": string;
    "repo_id": string;
    "branch_name": string;
    "base_branch_id"?: string | null;
    "first_seen_at"?: string;
  };
    "BulkDecisionItem": {
    "candidate_id": string;
  };
    "BulkDecisionRequest": {
    "review_id": string;
    "disposition": components["schemas"]["DecisionDisposition"];
    "author": string;
    "reasoning"?: string | null;
    "candidates": Array<components["schemas"]["BulkDecisionItem"]>;
  };
    "BulkDecisionResponse": {
    "recorded": number;
    "decisions": Array<components["schemas"]["DecisionResponse"]>;
  };
    "BundledExample": {
    "name": string;
    "title": string;
    "description": string;
    "repository_root": string;
  };
    "CandidateChangeResponse": {
    "candidate_id": string;
    "causes": Array<string>;
    "predecessor_id": string | null;
  };
    "CandidateResponse": {
    "id": string;
    "pattern": string;
    "summary": string;
    "participants": Array<components["schemas"]["ParticipantResponse"]>;
    "evidence": Array<components["schemas"]["EvidenceResponse"]>;
    "measurements": Array<components["schemas"]["MeasurementResponse"]>;
    "relationships": Array<components["schemas"]["RelationshipResponse"]>;
    "detection_rationale": string;
    "limitations": string;
  };
    "CaseAnswerDTO": {
    "question": string;
    "status": string;
    "value": string | null;
    "actor": string;
    "answered_at": string;
  };
    "CasePatch": {
    "policy_context"?: components["schemas"]["PolicyContextDTO"];
  };
    "CaseWrite": {
    "policy_context"?: components["schemas"]["PolicyContextDTO"];
  };
    "CheckoutRefresh": {
    "root_path": string;
    "managed"?: boolean;
    "updated"?: boolean;
    "branch_name"?: string | null;
  };
    "ConversationAnswerResponse": {
    "text": string;
    "supporting_candidate_ids": Array<string>;
    "investigation": components["schemas"]["RecordedInvestigationResponse"] | null;
  };
    "ConversationMessageResponse": {
    "question": string;
    "answer": components["schemas"]["ConversationAnswerResponse"];
    "asked_at": string;
  };
    "CyclesQuery": {
    "kind": "cyclic_components";
    "limit"?: number;
  };
    "DecisionDisposition": "accept" | "waive" | "park";
    "DecisionRequest": {
    "review_id": string;
    "candidate_id": string;
    "disposition": components["schemas"]["DecisionDisposition"];
    "author": string;
    "reasoning"?: string | null;
  };
    "DecisionResponse": {
    "id": string;
    "branch_id": string;
    "candidate_id": string;
    "disposition": string;
    "author": string;
    "reasoning": string | null;
    "decided_at": string;
    "review_id": string;
    "finding_verdict": string;
    "finding_model_identity": string;
    "finding_prompt_identity": string;
    "finding_retrieval_identity": string;
  };
    "DeltaResponse": {
    "unchanged": Array<string>;
    "changed": Array<components["schemas"]["CandidateChangeResponse"]>;
    "new": Array<string>;
    "addressed": Array<components["schemas"]["AddressedCandidateResponse"]>;
  };
    "DirectoryEntry": {
    "name": string;
    "path": string;
  };
    "DirectoryListing": {
    "path": string;
    "parent": string | null;
    "directories": Array<components["schemas"]["DirectoryEntry"]>;
  };
    "EdgeType": "contains" | "imports" | "calls" | "inherits" | "implements" | "references" | "tests" | "configures";
    "EmbeddingCatalogResponse": {
    "providers": Array<components["schemas"]["ProviderAvailabilityResponse"]>;
    "candidates": Array<components["schemas"]["EmbeddingModelResponse"]>;
  };
    "EmbeddingIdentity": {
    "provider": string;
    "model": string;
    "dimensions": number;
  };
    "EmbeddingModelResponse": {
    "provider": string;
    "model": string;
    "dimensions": number;
    "label"?: string;
    "is_selected"?: boolean;
  };
    "EmbeddingSelectionRequest": {
    "provider": string;
    "model": string;
  };
    "EvidenceResponse": {
    "description": string;
    "location": components["schemas"]["SourceLocationResponse"] | null;
    "excerpt": string | null;
    "note": string | null;
  };
    "FindingResponse": {
    "candidate": components["schemas"]["CandidateResponse"];
    "verdict": string;
    "reasoning": string;
    "policies": Array<components["schemas"]["PolicyBearingResponse"]>;
    "evidence": Array<components["schemas"]["EvidenceResponse"]>;
    "hinge": string | null;
    "recommended_response": string | null;
    "reused_from_review_id": string | null;
    "model_identity": string;
    "prompt_identity": string;
    "retrieval_identity": string;
    "investigation_identity": string;
  };
    "HotspotsQuery": {
    "kind": "hotspots";
    "metric": string;
    "limit"?: number;
  };
    "InvestigationLookupResponse": {
    "tool": string;
    "arguments": {
    [key: string]: string;
  };
    "result": string;
  };
    "MeasurementResponse": {
    "name": string;
    "value": number;
    "unit": string;
    "nature": string;
    "definition": string;
    "limitations": string;
  };
    "MetricNature": "objective_measurement" | "structural_proxy";
    "MetricScope": "lexical_node" | "owning_module" | "reverse_static_impact_neighbourhood" | "bounded_resolved_call_chain";
    "ModelCatalogResponse": {
    "providers": Array<components["schemas"]["ProviderAvailabilityResponse"]>;
    "candidates": Array<components["schemas"]["AvailableModelResponse"]>;
  };
    "ModelIdentity": {
    "provider": string;
    "model": string;
    "thinking"?: boolean | "minimal" | "low" | "medium" | "high" | null;
  };
    "ModelSelectionRequest": {
    "provider": string;
    "model": string;
    "thinking"?: boolean | "minimal" | "low" | "medium" | "high" | null;
  };
    "NeighbourhoodQuery": {
    "kind": "forward_neighbourhood" | "reverse_neighbourhood";
    "node_id": string;
    "depth"?: number;
    "limit"?: number;
  };
    "NodeDetailsQuery": {
    "kind": "node_details";
    "node_id": string;
  };
    "NodeType": "repository" | "package" | "module" | "class" | "function" | "method" | "interface" | "test_module" | "test_function" | "configuration";
    "ObscuritySignal": {
    "code": string;
    "message": string;
    "node_id": string;
    "location"?: components["schemas"]["SourceLocation"] | null;
    "nature"?: components["schemas"]["MetricNature"];
    "definition"?: string;
    "limitations"?: string;
  };
    "ParticipantResponse": {
    "qualified_name": string;
    "role": string;
    "node_id"?: string | null;
  };
    "PolicyBearingResponse": {
    "policy_id": string;
    "policy_title": string;
    "reasoning": string;
  };
    "PolicyContextDTO": {
    "user"?: string | null;
    "organisation"?: string | null;
    "repository"?: string | null;
  };
    "PolicyDocument": {
    "schema_version"?: 2;
    "id": string;
    "title": string;
    "description"?: string | null;
    "scope": components["schemas"]["PolicyScope"];
    "applies_to"?: string | null;
    "strength": components["schemas"]["PolicyStrength"];
    "tags": Array<string>;
    "source": components["schemas"]["PolicySource"];
    "body": string;
    "source_path": string;
    "content_hash": string;
    "origin"?: components["schemas"]["PolicyOrigin"];
  };
    "PolicyDraft": {
    "title": string;
    "description": string;
    "body": string;
    "tags"?: Array<string>;
    "strength": components["schemas"]["PolicyStrength"];
  };
    "PolicyOrigin": "external" | "workspace";
    "PolicyScope": "general" | "user" | "organisation" | "repository" | "accepted_adr";
    "PolicySource": {
    "author": string;
    "inspiration"?: Array<string>;
  };
    "PolicySourceRegistration": {
    "canonical_path": string;
    "registered_at"?: string;
  };
    "PolicySourceRemovalResponse": {
    "removed": boolean;
  };
    "PolicySourceRequest": {
    "source": string;
  };
    "PolicyStrength": "guidance" | "preferred" | "required";
    "ProblemDetail": {
    "code": string;
    "message": string;
    "retryable"?: boolean;
    "field_errors"?: Array<string>;
  };
    "ProviderAvailabilityResponse": {
    "provider": string;
    "available": boolean;
    "detail"?: string;
    "label"?: string;
    "probed_at": string;
  };
    "QuestionResponse": {
    "id": string;
    "text": string;
    "facet": string;
    "candidate_ids": Array<string>;
    "round": number;
    "equivalence_key": string;
    "options": Array<string>;
  };
    "RecordedInvestigationResponse": {
    "candidate_id": string;
    "lookups": Array<components["schemas"]["InvestigationLookupResponse"]>;
    "closing": string;
    "withheld": string;
    "termination": components["schemas"]["Termination"] | null;
    "atlas_fingerprint": string;
    "prompt_identity": string;
    "model_identity": string;
  };
    "RelationQuery": {
    "kind": "direct_dependencies" | "direct_dependants" | "known_callers" | "implementations" | "related_tests";
    "node_id": string;
    "limit"?: number;
  };
    "RelationshipResponse": {
    "source": string;
    "target": string;
    "kind": string;
    "resolved_by": string;
  };
    "RepositoryBranch": {
    "repository": components["schemas"]["RepositoryLineage"];
    "branch": components["schemas"]["BranchLineage"];
  };
    "RepositoryCheckout": {
    "root_path": string;
    "branch_name"?: string | null;
    "created"?: boolean;
    "managed"?: boolean;
  };
    "RepositoryCheckoutRequest": {
    "url": string;
    "branch"?: string | null;
  };
    "RepositoryFolder": {
    "path": string;
    "python_files": number;
    "python_bytes": number;
    "suggested"?: boolean;
  };
    "RepositoryFolderTree": {
    "root_path": string;
    "folders"?: Array<components["schemas"]["RepositoryFolder"]>;
    "total_python_files"?: number;
    "total_python_bytes"?: number;
  };
    "RepositoryIndexRequest": {
    "root_path": string;
    "excluded_paths"?: Array<string> | null;
  };
    "RepositoryLineage": {
    "repo_id": string;
    "root_commit_sha"?: string | null;
    "canonical_root": string;
    "first_seen_at"?: string;
  };
    "RepositoryPathRequest": {
    "root_path": string;
  };
    "RepositoryResponse": {
    "id": string;
    "path": string;
    "branch_id": string;
    "content_id": string;
    "remote_url": string | null;
    "branch": string | null;
    "commit": string | null;
  };
    "RepositorySummary": {
    "version_id": string;
    "repository_identity": string;
    "root_path": string;
    "git_commit_sha"?: string | null;
    "repo_id"?: string | null;
    "branch_name"?: string | null;
    "created_at": string;
    "snapshot_count"?: number;
    "head_commit_sha"?: string | null;
    "commits_behind"?: number | null;
    "excluded_path_count"?: number;
    "node_count"?: number;
    "edge_count"?: number;
    "signal_count"?: number;
  };
    "RepositorySummaryQuery": {
    "kind": "repository_summary";
    "limit"?: number;
  };
    "RetrievalProvenanceResponse": {
    "candidate_id": string;
    "retriever": string;
    "version": string;
    "corpus_fingerprint": string;
    "selected_policy_ids": Array<string>;
    "model_identity": string | null;
    "query_fingerprint": string | null;
    "metadata": {
    [key: string]: string;
  };
  };
    "ReviewAnswersRequest": {
    "answers"?: Array<components["schemas"]["SubmittedAnswerRequest"]>;
    "stop"?: boolean;
  };
    "ReviewContextQuery": {
    "kind": "review_context";
    "node_ids"?: Array<string>;
    "qualified_names"?: Array<string>;
    "limit"?: number;
  };
    "ReviewContextRequest": {
    "root_path": string;
    "node_ids"?: Array<string>;
    "qualified_names"?: Array<string>;
    "limit"?: number;
  };
    "ReviewConversationCreateRequest": {
    "review_id": string;
  };
    "ReviewConversationResponse": {
    "id": string;
    "review_id": string;
    "messages": Array<components["schemas"]["ConversationMessageResponse"]>;
  };
    "ReviewQuestionRequest": {
    "question": string;
  };
    "ReviewRequest": {
    "case_id": string;
    "repository_root": string;
    "case_revision"?: number | null;
    "ci"?: boolean;
  };
    "ReviewResponse": {
    "id": string;
    "sequence": number;
    "round": number;
    "status": string;
    "previous_review_id": string | null;
    "repository": components["schemas"]["RepositoryResponse"];
    "atlas": components["schemas"]["AtlasResponse"];
    "case": components["schemas"]["archcompass__presentation__web__routes__reviews__CaseResponse"];
    "findings": Array<components["schemas"]["FindingResponse"]>;
    "questions": Array<components["schemas"]["QuestionResponse"]>;
    "delta": components["schemas"]["DeltaResponse"];
    "retrieval_manifest": Array<components["schemas"]["RetrievalProvenanceResponse"]>;
    "investigation_manifest": Array<components["schemas"]["RecordedInvestigationResponse"]>;
    "synopsis": string | null;
    "synopsis_identity": string;
    "model_identity": string;
    "prompt_identity": string;
    "started_at": string;
    "finished_at": string | null;
    "failure": string | null;
  };
    "ReviewRunResponse": {
    "run_id": string;
    "status": string;
    "review_id": string | null;
    "stage": string;
    "stages": Array<string>;
    "failure": string;
    "candidates_to_judge"?: number;
    "candidates_judged"?: number;
    "batch"?: string;
    "repository_name"?: string;
    "repository_root"?: string;
    "excluded_paths"?: Array<string>;
    "branch_name"?: string;
    "branch_id"?: string;
    "case_id"?: string;
    "sequence"?: number;
    "started_at"?: string | null;
  };
    "ReviewSummaryResponse": {
    "id": string;
    "sequence": number;
    "round": number;
    "status": string;
    "previous_review_id": string | null;
    "repository": components["schemas"]["RepositoryResponse"];
    "case_id": string;
    "case_revision": number;
    "answer_count": number;
    "started_at": string;
    "finished_at": string | null;
    "finding_count": number;
    "material_count": number;
    "held_count": number;
    "cleared_count": number;
    "question_count": number;
    "unchanged_count": number;
    "changed_count": number;
    "new_count": number;
    "addressed_count": number;
  };
    "SearchNodesQuery": {
    "kind": "search_nodes";
    "terms": Array<string>;
    "limit"?: number;
  };
    "ShortestPathQuery": {
    "kind": "shortest_dependency_path";
    "source_id": string;
    "target_id": string;
  };
    "SignalsQuery": {
    "kind": "signals";
    "codes"?: Array<string>;
    "limit"?: number;
  };
    "SourceExcerpt": {
    "node_id": string;
    "location": components["schemas"]["SourceLocation"];
    "text": string;
  };
    "SourceExcerptQuery": {
    "kind": "source_excerpt";
    "node_id": string;
    "context_lines"?: number;
    "max_lines"?: number;
  };
    "SourceLocation": {
    "path": string;
    "start_line": number;
    "end_line": number;
  };
    "SourceLocationResponse": {
    "path": string;
    "start_line": number;
    "end_line": number;
  };
    "StartFromRepositoryRequest": {
    "root_path": string;
    "start_clean"?: boolean;
    "excluded_paths"?: Array<string> | null;
  };
    "StartedCaseResponse": {
    "case_id": string;
    "revision": number;
  };
    "SubmittedAnswerRequest": {
    "question_id": string;
    "status": components["schemas"]["AnswerStatus"];
    "value"?: string | null;
    "actor"?: string;
  };
    "SubsystemSummaryQuery": {
    "kind": "subsystem_summary";
    "node_id": string;
    "limit"?: number;
  };
    "Termination": "natural_end" | "model_call_limit" | "lookup_limit" | "investigation_size_limit" | "timeout" | "provider_error";
    "WorkspaceModels": {
    "reasoning"?: components["schemas"]["ModelIdentity"] | null;
    "embedding"?: components["schemas"]["EmbeddingIdentity"] | null;
    "failure"?: string;
    "pinned"?: boolean;
    "embedding_pinned"?: boolean;
  };
    "WorkspaceSummaryResponse": {
    "workspace": string;
    "models": components["schemas"]["WorkspaceModels"];
    "hosted"?: boolean;
    "source_hosts"?: Array<string>;
  };
    "archcompass__presentation__web__routes__cases__CaseResponse": {
    "case_id": string;
    "revision": number;
    "answers": Array<components["schemas"]["CaseAnswerDTO"]>;
    "policy_context": components["schemas"]["PolicyContextDTO"];
    "created_at": string;
    "updated_at": string;
  };
    "archcompass__presentation__web__routes__reviews__CaseResponse": {
    "id": string;
    "revision": number;
    "answers": Array<components["schemas"]["AnswerResponse"]>;
    "created_at": string;
    "updated_at": string;
  };
  };
}

export interface operations {
  "add_policy_source_api_policies_sources_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["PolicySourceRequest"];
    responses: {
      "201": components["schemas"]["PolicySourceRegistration"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "answer_review_api_reviews__review_id__answers_post": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewAnswersRequest"];
    responses: {
      "200": components["schemas"]["ReviewResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "answer_review_run_api_reviews__review_id__answers_runs_post": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewAnswersRequest"];
    responses: {
      "202": components["schemas"]["ReviewRunResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "ask_review_question_api_review_conversations__conversation_id__messages_post": {
    parameters: {
      query: never;
      path: {
      "conversation_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewQuestionRequest"];
    responses: {
      "200": components["schemas"]["ReviewConversationResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "branch_decisions_api_branches__branch_id__decisions_get": {
    parameters: {
      query: never;
      path: {
      "branch_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["BranchDecisionsResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "cancel_review_api_reviews__review_id__cancel_post": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ReviewResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "cancel_review_run_api_reviews_runs__run_id__cancel_post": {
    parameters: {
      query: never;
      path: {
      "run_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ReviewRunResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "case_history_api_cases__case_id__history_get": {
    parameters: {
      query: never;
      path: {
      "case_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["archcompass__presentation__web__routes__cases__CaseResponse"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "checkout_repository_api_repositories_checkout_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["RepositoryCheckoutRequest"];
    responses: {
      "201": components["schemas"]["RepositoryCheckout"];
      "422": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "clear_embedding_selection_api_embeddings_selection_delete": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "clear_model_selection_api_models_selection_delete": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "create_case_api_cases_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["CaseWrite"];
    responses: {
      "201": components["schemas"]["archcompass__presentation__web__routes__cases__CaseResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "create_policy_api_policies_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["PolicyDraft"];
    responses: {
      "201": components["schemas"]["PolicyDocument"];
      "422": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "create_review_api_reviews_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewRequest"];
    responses: {
      "201": components["schemas"]["ReviewResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "create_review_conversation_api_review_conversations_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewConversationCreateRequest"];
    responses: {
      "201": components["schemas"]["ReviewConversationResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "decision_history_api_decisions__branch_id___candidate_id__history_get": {
    parameters: {
      query: never;
      path: {
      "branch_id": string;
      "candidate_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["DecisionResponse"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "delete_policy_api_policies__policy_id__delete": {
    parameters: {
      query: never;
      path: {
      "policy_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "delete_review_api_reviews__review_id__delete": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "delete_review_conversation_api_review_conversations__conversation_id__delete": {
    parameters: {
      query: never;
      path: {
      "conversation_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "204": unknown;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "embedding_catalog_api_embeddings_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["EmbeddingCatalogResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "get_case_api_cases__case_id__get": {
    parameters: {
      query: {
      "revision"?: number | null;
      };
      path: {
      "case_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["archcompass__presentation__web__routes__cases__CaseResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "get_policy_api_policies__policy_id__get": {
    parameters: {
      query: {
      "repository_root"?: string | null;
      };
      path: {
      "policy_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["PolicyDocument"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "get_review_api_reviews__review_id__get": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ReviewResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "get_review_conversation_api_review_conversations__conversation_id__get": {
    parameters: {
      query: never;
      path: {
      "conversation_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ReviewConversationResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "get_review_report_api_reviews__review_id__report_get": {
    parameters: {
      query: never;
      path: {
      "review_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": unknown;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "import_case_yaml_api_cases_import_yaml_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: string;
    responses: {
      "201": components["schemas"]["archcompass__presentation__web__routes__cases__CaseResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "index_repository_api_repositories_index_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["RepositoryIndexRequest"];
    responses: {
      "201": components["schemas"]["AtlasVersion"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_branches_api_branches_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["RepositoryBranch"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_cases_api_cases_get": {
    parameters: {
      query: {
      "limit"?: number;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["archcompass__presentation__web__routes__cases__CaseResponse"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_directories_api_filesystem_directories_get": {
    parameters: {
      query: {
      "path"?: string | null;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["DirectoryListing"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_examples_api_examples_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["BundledExample"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_policies_api_policies_get": {
    parameters: {
      query: {
      "repository_root"?: string | null;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["PolicyDocument"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_policy_sources_api_policies_sources_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["PolicySourceRegistration"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_remote_branches_api_repositories_remote_branches_get": {
    parameters: {
      query: {
      "url": string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<string>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_repositories_api_repositories_get": {
    parameters: {
      query: {
      "limit"?: number;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["RepositorySummary"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_review_conversations_api_review_conversations_get": {
    parameters: {
      query: {
      "review_id": string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["ReviewConversationResponse"]>;
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "list_review_runs_api_reviews_runs_get": {
    parameters: {
      query: {
      "limit"?: number;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["ReviewRunResponse"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "list_reviews_api_reviews_get": {
    parameters: {
      query: {
      "limit"?: number;
      "view"?: "full" | "summary";
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": Array<components["schemas"]["ReviewResponse"]> | Array<components["schemas"]["ReviewSummaryResponse"]>;
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "load_example_api_examples__name__load_post": {
    parameters: {
      query: never;
      path: {
      "name": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "201": components["schemas"]["AtlasVersion"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "model_catalog_api_models_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ModelCatalogResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "read_review_run_api_reviews_runs__run_id__get": {
    parameters: {
      query: never;
      path: {
      "run_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["ReviewRunResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "record_decision_api_decisions_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["DecisionRequest"];
    responses: {
      "201": components["schemas"]["DecisionResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "record_decisions_api_decisions_bulk_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["BulkDecisionRequest"];
    responses: {
      "201": components["schemas"]["BulkDecisionResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "refresh_repository_api_repositories_refresh_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["RepositoryPathRequest"];
    responses: {
      "200": components["schemas"]["CheckoutRefresh"];
      "422": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "remove_policy_source_api_policies_sources_delete": {
    parameters: {
      query: {
      "source": string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["PolicySourceRemovalResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_explore_api_repositories_explore_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["AtlasExploreRequest"];
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_hotspots_api_repositories_hotspots_get": {
    parameters: {
      query: {
      "root_path": string;
      "metric"?: string;
      };
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_review_context_api_repositories_review_context_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewContextRequest"];
    responses: {
      "200": components["schemas"]["AtlasQueryResult"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "repository_tree_api_repositories_tree_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["RepositoryPathRequest"];
    responses: {
      "200": components["schemas"]["RepositoryFolderTree"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "rescope_case_api_cases__case_id__patch": {
    parameters: {
      query: never;
      path: {
      "case_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["CasePatch"];
    responses: {
      "200": components["schemas"]["archcompass__presentation__web__routes__cases__CaseResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
  "select_embedding_model_api_embeddings_selection_put": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["EmbeddingSelectionRequest"];
    responses: {
      "200": components["schemas"]["WorkspaceSummaryResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "select_model_api_models_selection_put": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ModelSelectionRequest"];
    responses: {
      "200": components["schemas"]["WorkspaceSummaryResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "start_from_repository_api_repositories_start_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["StartFromRepositoryRequest"];
    responses: {
      "200": components["schemas"]["StartedCaseResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
    };
  };
  "start_review_run_api_reviews_runs_post": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["ReviewRequest"];
    responses: {
      "202": components["schemas"]["ReviewRunResponse"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "503": components["schemas"]["ProblemDetail"];
    };
  };
  "update_policy_api_policies__policy_id__put": {
    parameters: {
      query: never;
      path: {
      "policy_id": string;
      };
      header: never;
      cookie: never;
    };
    requestBody: components["schemas"]["PolicyDraft"];
    responses: {
      "200": components["schemas"]["PolicyDocument"];
      "422": components["schemas"]["ProblemDetail"];
      "404": components["schemas"]["ProblemDetail"];
      "409": components["schemas"]["ProblemDetail"];
    };
  };
  "workspace_summary_api_workspace_get": {
    parameters: {
      query: never;
      path: never;
      header: never;
      cookie: never;
    };
    requestBody?: never;
    responses: {
      "200": components["schemas"]["WorkspaceSummaryResponse"];
      "422": components["schemas"]["ProblemDetail"];
    };
  };
}

export interface paths {
  "/api/branches": {
    get: operations["list_branches_api_branches_get"];
  };
  "/api/branches/{branch_id}/decisions": {
    get: operations["branch_decisions_api_branches__branch_id__decisions_get"];
  };
  "/api/cases": {
    get: operations["list_cases_api_cases_get"];
    post: operations["create_case_api_cases_post"];
  };
  "/api/cases/import-yaml": {
    post: operations["import_case_yaml_api_cases_import_yaml_post"];
  };
  "/api/cases/{case_id}": {
    get: operations["get_case_api_cases__case_id__get"];
    patch: operations["rescope_case_api_cases__case_id__patch"];
  };
  "/api/cases/{case_id}/history": {
    get: operations["case_history_api_cases__case_id__history_get"];
  };
  "/api/decisions": {
    post: operations["record_decision_api_decisions_post"];
  };
  "/api/decisions/bulk": {
    post: operations["record_decisions_api_decisions_bulk_post"];
  };
  "/api/decisions/{branch_id}/{candidate_id}/history": {
    get: operations["decision_history_api_decisions__branch_id___candidate_id__history_get"];
  };
  "/api/embeddings": {
    get: operations["embedding_catalog_api_embeddings_get"];
  };
  "/api/embeddings/selection": {
    put: operations["select_embedding_model_api_embeddings_selection_put"];
    delete: operations["clear_embedding_selection_api_embeddings_selection_delete"];
  };
  "/api/examples": {
    get: operations["list_examples_api_examples_get"];
  };
  "/api/examples/{name}/load": {
    post: operations["load_example_api_examples__name__load_post"];
  };
  "/api/filesystem/directories": {
    get: operations["list_directories_api_filesystem_directories_get"];
  };
  "/api/models": {
    get: operations["model_catalog_api_models_get"];
  };
  "/api/models/selection": {
    put: operations["select_model_api_models_selection_put"];
    delete: operations["clear_model_selection_api_models_selection_delete"];
  };
  "/api/policies": {
    get: operations["list_policies_api_policies_get"];
    post: operations["create_policy_api_policies_post"];
  };
  "/api/policies/sources": {
    get: operations["list_policy_sources_api_policies_sources_get"];
    post: operations["add_policy_source_api_policies_sources_post"];
    delete: operations["remove_policy_source_api_policies_sources_delete"];
  };
  "/api/policies/{policy_id}": {
    get: operations["get_policy_api_policies__policy_id__get"];
    put: operations["update_policy_api_policies__policy_id__put"];
    delete: operations["delete_policy_api_policies__policy_id__delete"];
  };
  "/api/repositories": {
    get: operations["list_repositories_api_repositories_get"];
  };
  "/api/repositories/checkout": {
    post: operations["checkout_repository_api_repositories_checkout_post"];
  };
  "/api/repositories/explore": {
    post: operations["repository_explore_api_repositories_explore_post"];
  };
  "/api/repositories/hotspots": {
    get: operations["repository_hotspots_api_repositories_hotspots_get"];
  };
  "/api/repositories/index": {
    post: operations["index_repository_api_repositories_index_post"];
  };
  "/api/repositories/refresh": {
    post: operations["refresh_repository_api_repositories_refresh_post"];
  };
  "/api/repositories/remote-branches": {
    get: operations["list_remote_branches_api_repositories_remote_branches_get"];
  };
  "/api/repositories/review-context": {
    post: operations["repository_review_context_api_repositories_review_context_post"];
  };
  "/api/repositories/start": {
    post: operations["start_from_repository_api_repositories_start_post"];
  };
  "/api/repositories/tree": {
    post: operations["repository_tree_api_repositories_tree_post"];
  };
  "/api/review-conversations": {
    get: operations["list_review_conversations_api_review_conversations_get"];
    post: operations["create_review_conversation_api_review_conversations_post"];
  };
  "/api/review-conversations/{conversation_id}": {
    get: operations["get_review_conversation_api_review_conversations__conversation_id__get"];
    delete: operations["delete_review_conversation_api_review_conversations__conversation_id__delete"];
  };
  "/api/review-conversations/{conversation_id}/messages": {
    post: operations["ask_review_question_api_review_conversations__conversation_id__messages_post"];
  };
  "/api/reviews": {
    get: operations["list_reviews_api_reviews_get"];
    post: operations["create_review_api_reviews_post"];
  };
  "/api/reviews/runs": {
    get: operations["list_review_runs_api_reviews_runs_get"];
    post: operations["start_review_run_api_reviews_runs_post"];
  };
  "/api/reviews/runs/{run_id}": {
    get: operations["read_review_run_api_reviews_runs__run_id__get"];
  };
  "/api/reviews/runs/{run_id}/cancel": {
    post: operations["cancel_review_run_api_reviews_runs__run_id__cancel_post"];
  };
  "/api/reviews/{review_id}": {
    get: operations["get_review_api_reviews__review_id__get"];
    delete: operations["delete_review_api_reviews__review_id__delete"];
  };
  "/api/reviews/{review_id}/answers": {
    post: operations["answer_review_api_reviews__review_id__answers_post"];
  };
  "/api/reviews/{review_id}/answers/runs": {
    post: operations["answer_review_run_api_reviews__review_id__answers_runs_post"];
  };
  "/api/reviews/{review_id}/cancel": {
    post: operations["cancel_review_api_reviews__review_id__cancel_post"];
  };
  "/api/reviews/{review_id}/report": {
    get: operations["get_review_report_api_reviews__review_id__report_get"];
  };
  "/api/workspace": {
    get: operations["workspace_summary_api_workspace_get"];
  };
}
